### ISSUE TITLE
 Design Optimierung: Button "Analyse anzeigen" fehlt

### ISSUE THREAD

**Issue by Riccardalina** [Abonax-SAL/Waermekachel-TBW#14]
Auf der Seite fehlt der Button
![Bild 4](https://user-images.githubusercontent.com/122005698/214515232-1d3e2e23-185f-4fd6-97a0-fb34193e05b9.jpg)

Hier das Beispiel aus dem Aufgabenkatalog
![Bild1](https://user-images.githubusercontent.com/122005698/214515260-cd42c675-1337-4b2f-80f9-24dcd4a3629a.png)

**Comment by christoph-menzi** [comment]
Scheint eher ein Cache-Problem zu sein. Bei mir wird es korrekt angezeigt.

Getestet mit Chrome Inkognito / Firefox Privates Fenster / BrowserStack diverse Browser / OS
