### ISSUE TITLE
Design Optimierung: Kästchen "Wärme" fehlt bei Kontaktformular

### ISSUE THREAD

**Issue by Riccardalina** [Abonax-SAL/Waermekachel-TBW#15]
Hier fehtl das Kästchen "Wärme/Fernwärme" (siehe Bild unten)
![Bild 5](https://user-images.githubusercontent.com/122005698/214515969-02006f45-dd17-4223-99c5-9d63db1df86c.jpg)

Bild aus der Datenansichtsvorlage
![Unbenanntneu](https://user-images.githubusercontent.com/122005698/214516084-e94c9e4d-5533-46b9-93bc-76ae7d1bdbdc.JPG)

**Comment by christoph-menzi** [comment]
Die Daten werden von der Seite "Lösungen" geholt. Automatisch. Das sind die Kacheln unten mit Bild/Text. Gibt es für diesen Bereich in Zukunft auch eine eigene Kachel oder soll ich den Punkt von Hand (hartgecodet) einfügen?

![image](https://user-images.githubusercontent.com/109087392/214543202-4aa21f64-61f3-4aeb-ba76-d6e14f658842.png)

**Comment by Riccardalina** [comment]
@christoph-menzi : ok das war mir nicht klar. Dann bitte folgende Kategorien ergänzen: 
- Fernwärme 
- Contracting

Und die Überschrift: Unsere Lösungen für Wärme

Bild Fernwärme (Platzhalter): https://we.tl/t-xi3b0VskrP
Bild Contracting: https://we.tl/t-RfMVFn8tbt

**Comment by christoph-menzi** [comment]
Ist hinterlegt. 

Bei den einzelnen Wärme-Lösungen müsste man noch definieren welcher Gebäudenutzer es ist.

![image](https://user-images.githubusercontent.com/109087392/215524844-c8f42de9-c2ac-4cb4-b2ad-acb619da6652.png)

**Comment by Riccardalina** [comment]
> Ist hinterlegt.
> 
> Bei den einzelnen Wärme-Lösungen müsste man noch definieren welcher Gebäudenutzer es ist.
> 
> ![image](https://user-images.githubusercontent.com/109087392/215524844-c8f42de9-c2ac-4cb4-b2ad-acb619da6652.png)

angezeigt wird momentan aber nur Wärmelösung und der Titel unten im Wissens Hub fehlt

**Comment by Riccardalina** [comment]
@christoph-menzi: alle Wärme Themen finden sich jetzt unter dem Titel E-Mobilität - die Wärme Themen benötigen noch einen separaten Titel wie oben beschrieben (Überschrift: Unsere Lösungen für Wärme)

**Comment by christoph-menzi** [comment]
Ist angepasst.
