### ISSUE TITLE
Design Optimierung: Satz in Kachel entfernen

### ISSUE THREAD

**Issue by Riccardalina** [Abonax-SAL/Waermekachel-TBW#16]
Diese Angabe wird unterhalb aller Kacheln erwähnt und muss nicht direkt in der Kachel selbst nochmals aufgeführt sein. bitte löschen.
![Bild 6](https://user-images.githubusercontent.com/122005698/214517175-16ebb6c0-421e-4551-baf4-0263f19606fd.jpg)

**Comment by christoph-menzi** [comment]
habe ich entfernt.
