### ISSUE TITLE
Design Optimierung: Logo dreht sich 

### ISSUE THREAD

**Issue by Riccardalina** [Abonax-SAL/Waermekachel-TBW#18]
Das Logo sollte sich eigentlich nicht ständig drehen, sondern nur beim scrollen (siehe bestehende Seite). Bitte dies wieder rückgängig machen. Die transparente Farbe sollte aber genau so bleiben.

![grafik](https://user-images.githubusercontent.com/122005698/214519159-db49126b-19aa-43b7-a505-ee4fa82d39c3.png)

**Comment by christoph-menzi** [comment]
Ist angepasst.

**Comment by Riccardalina** [comment]
@christoph-menzi : Jetzt dreht es sich gar nicht mehr - bitte genau so übernehmen wie auf der aktuellen seite

**Comment by christoph-menzi** [comment]
Doch, es dreht sich doch. Jedenfalls bei mir. :-)

https://visions.tinytake.com/df/13e9dc4/thumbnail?type=attachments&version_no=0&file_version_no=0&thumbnail_size=preview

**Comment by Riccardalina** [comment]
du hast recht :-) mein fehler sorry!
