### ISSUE TITLE
Design Optimierung: Bild "Dach vermieten" austauschen

### ISSUE THREAD

**Issue by Riccardalina** [Abonax-SAL/Waermekachel-TBW#20]
Bestehendes Bild durch untenstehendes austauschen.
![Unbenannt3](https://user-images.githubusercontent.com/122005698/214520599-4808d4d4-bdee-481e-87f6-a8371e762767.JPG)

Neues Bild: https://we.tl/t-SNloyQJKBX

**Comment by christoph-menzi** [comment]
Bild ist ausgetauscht
