### ISSUE TITLE
Design Optimierung: Bild und Text bei "Lademanagement" ersetzen

### ISSUE THREAD

**Issue by Riccardalina** [Abonax-SAL/Waermekachel-TBW#21]
![Bild 9](https://user-images.githubusercontent.com/122005698/214521153-2741dcb4-8890-45c1-8836-d993ea08d2c6.jpg)

Neues Bild: https://we.tl/t-bQc1YP8JRs

**Comment by christoph-menzi** [comment]
Bild ausgetauscht. Titel angepasst.
