### ISSUE TITLE
Design Optimierung: Bild bei "Ladestation" ersetzen

### ISSUE THREAD

**Issue by Riccardalina** [Abonax-SAL/Waermekachel-TBW#23]
Bild ersetzen
![Bild 11](https://user-images.githubusercontent.com/122005698/214522039-61506a4b-f753-4a6b-9cf1-96d5f158272d.jpg)

Neues Bild: https://we.tl/t-ebe3HHlEP2

**Comment by christoph-menzi** [comment]
Bild wurde ausgetauscht.
