### ISSUE TITLE
Design Optimierung: Titelbild ändern

### ISSUE THREAD

**Issue by Riccardalina** [Abonax-SAL/Waermekachel-TBW#24]
Das grosse Titelbild ersetzn durch untenstehendes
![Unbenannt8](https://user-images.githubusercontent.com/122005698/214523334-5406808a-651b-4489-9824-702ef9456816.JPG)

Neues Bild: https://we.tl/t-A9LBQiuQTb

**Comment by christoph-menzi** [comment]
Bild ausgetauscht. Auflösung könnte besser sein. Idealerweise ca. 2500px breite.
