### ISSUE TITLE
Design Optimierung: Responsive Design anpassen

### ISSUE THREAD

**Issue by Riccardalina** [Abonax-SAL/Waermekachel-TBW#25]
Text liegt übereinander

![grafik](https://user-images.githubusercontent.com/122005698/215036668-005e4c03-d9c8-4aa9-aff3-d3f1a9f29fa2.png)

**Comment by christoph-menzi** [comment]
Aber einer Grösse von 767px wird der Text rechts aussen ausgeblendet.

Alternativ könnte man auch die 4 Schritte-Buttons ausblenden oder linksbündig machen.

Die Frage ist > Was ist wichtiger? Text oder die Buttons (Smartphone)

**Comment by christoph-menzi** [comment]
Text ist nun linksbündig und nach oben verlagert.

![image](https://user-images.githubusercontent.com/109087392/218026633-37bfb604-a7d5-4f58-a847-17a5a6887dbc.png)
