### ISSUE TITLE
Design Optimierung: Call to actions

### ISSUE THREAD

**Issue by Riccardalina** [Abonax-SAL/Waermekachel-TBW#26]
Aus meiner Sicht fehlen hier bei allen Themen noch CTA's - entweder Buttons oder unterstrichene Links mit der Bezeichnung: Zum Produkt

![grafik](https://user-images.githubusercontent.com/122005698/215037450-cc601924-dd12-4829-ba67-2af6ecdfb483.png)

**Comment by christoph-menzi** [comment]
Ist angepasst / gefixt.

**Comment by Riccardalina** [comment]
@christoph-menzi : sieht gut aus, danke. Bitte noch den ersten Buchstabe jeweils gross schreiben "Zum Produkt"
ausserdem bitte texte wiefolgt anpassen:

Ladestation: Zum Produkt
Wärmelösungen: Zu den Lösungen

**Comment by christoph-menzi** [comment]
Das kann pro Lösung definiert werden. Der Link stimmt so vermutlich auch noch nicht.

![image](https://user-images.githubusercontent.com/109087392/215530188-d5012eb3-c2b4-41e3-a8b1-610c41dd9727.png)

**Comment by christoph-menzi** [comment]
Die Links habe ich nun alle angepasst.
