### ISSUE TITLE
Darstellung der Kachel auf bestehender Landingpage

### ISSUE THREAD

**Issue by Riccardalina** [Abonax-SAL/Waermekachel-TBW#27]
Die momentan noch aktive Landingpage mit dem alten Design stellt die Kacheln untereinander anstatt nebeneinander dar, bitte beheben.
![grafik](https://user-images.githubusercontent.com/122005698/215048177-5ce7ee72-0803-474f-bcce-cf6a75bb2515.png)

**Comment by christoph-menzi** [comment]
Gefixt
