### ISSUE TITLE
Zusätzliche Variablen für E-Mobilität

### ISSUE THREAD

**Issue by Abonax-SAL** [Abonax-SAL/Waermekachel-TBW#28]
Info von Chris:

Falls weitere Variablen in das Excel eingefügt werden sollen, einfach am Ende Spalten einfügen. Allenfalls braucht es noch die Information, dass die neuen Spalten der zweiten Kachel EV zugeordnet werden sollen.

![image](https://user-images.githubusercontent.com/121949345/215062650-7b1beaf3-589b-4cb9-a540-258657286f0b.png)

**Comment by mguddelmoni** [comment]
Momentan kommen die Daten für E-Mobilität von einer anderen Datenquelle. Die Verarbeitung der Excel für diesen Zweck kommt erst in Frag wenn wir die Kachel Mobilität komplett über das Excel abwickeln.
