### ISSUE TITLE
Darstellung Kacheln linksbündig anpassen

### ISSUE THREAD

**Issue by Riccardalina** [Abonax-SAL/Waermekachel-TBW#30]
Bitte die Texte in den Kacheln linksbündig anpassen:
![grafik](https://user-images.githubusercontent.com/122005698/215755257-e993e9cb-372d-4e00-b7c6-18e159646eeb.png)

**Comment by christoph-menzi** [comment]
Ist angepasst. 
![image](https://user-images.githubusercontent.com/109087392/215756782-b2ef5cc8-5204-4642-93b2-30f5678f331a.png)
