### ISSUE TITLE
Logik noch zu lösen: Was geschieht mit Adressen 8.1, 8.2

### ISSUE THREAD

**Issue by Abonax-SAL** [Abonax-SAL/Waermekachel-TBW#32]
Sali Mirko

Sieht super aus. Schnell und von der Funktionalität fast perfekt.

Etwas habe ich noch gefunden:

Die Adresse mit … 8.2 findet man bei den Daten von SEP. Bei uns nicht. Das hat einen konkreten Grund, denn wir weisen alle Adressen wie 8.1,  8.2 etc. der Stammadresse 8 zu.

Die Funktionalität sollte aber so sein, dass in diesen Fällen einfach die Solarkachel eingeblendet wird und die E-Mobility-Kachel ebenfalls. Die Wärmekachel sollte ebenfalls erscheinen aber eine Meldung, dass die Adresse nicht in unserer Datenbank enthalten ist. (So wie das ja im Fall 1 od. 5 schon vorgesehen ist.)

Kriegst Du da so hin?

**Comment by mguddelmoni** [comment]
Das geht leider nicht, da die Schnittstelle eine andere EGID ausgibt
