### ISSUE TITLE
Darstellen, dass WP nicht möglich ist

### ISSUE THREAD

**Issue by Abonax-SAL** [Abonax-SAL/Waermekachel-TBW#33]
Wenn Erdsondenbohrgebiet, dann soll bei den Lösungen angezeigt werden, dass die Bohrung voraussichtich nicht erlaubt ist.

@AndreasEgli: Kannst Du das in der Exportliste aufnehmen? "voraussichtlich nicht erlaubt"
@mguddelmoni : Ist es möglich in einem Feld Zahlen (Invesitionskosten) und Text (voraussichtlich nicht erlaubt") zu haben?
@christoph-menzi; Kannst Du Ausgabe so gestalten? ( in diesem Fall werden keine Investitionskosten dargestellt)
         3. Erdsonden Wärmepumpe:   voraussichtlich nicht erlaubt

![image](https://user-images.githubusercontent.com/121949345/216119212-e9c6cb7f-3d5c-4345-8f99-3e7868ceb4cb.png)

![image](https://user-images.githubusercontent.com/121949345/216119188-5cba35ee-63c1-4d9e-8f09-1220b63b5250.png)

**Comment by AndreasEgli** [comment]
Habe eine Zelle "AB" eingefügt im Excel für WP nicht möglich. Wenn dort ein "X" drin steht muss folgendes geschehen: "3. Erdsonden-Wärmepumpe:     In der Regel nicht zulässig" 
Die Erdsonden-Wärmepumpe soll dann immer als 3. Option erscheinen, wenn in der Zelle "AB" ein "X" drin ist.

![image](https://user-images.githubusercontent.com/122540658/217224192-d721f7bb-8696-49fb-a605-8847b6e749d0.png)

**Comment by mguddelmoni** [comment]
Es ist möglich Zahlen und  Text zu mischen. Dies muss aber so implementiert und abgefangen werden von unserer Seite.
