### ISSUE TITLE
Bildgrösse passt sich nicht automatisch an

### ISSUE THREAD

**Issue by Riccardalina** [Abonax-SAL/Waermekachel-TBW#37]
![image](https://user-images.githubusercontent.com/122005698/223966436-87fd0611-ffad-49b2-90b8-08a68ba8b25e.png)

**Comment by mguddelmoni** [comment]
Das Bild war mit 6000 Pixeln zu gross, daher wurde das Bild nicht automatisch gerechnet.
Ich habe das Bild nun komprimiert.
