### ISSUE TITLE
Icon Wärme austauschen

### ISSUE THREAD

**Issue by Abonax-SAL** [Abonax-SAL/Waermekachel-TBW#7]
![image](https://user-images.githubusercontent.com/121949345/213664142-727a5e79-4050-45e6-9a84-667f6ebf70e4.png)

Chris hat einfach einmal ein Icon verwendet. Falls Du ein anderes haben möchtest dann ihm bitte schicken.

**Comment by Riccardalina** [comment]
![heating](https://user-images.githubusercontent.com/122005698/214117776-1ae2d4d8-8ea5-4ddd-b981-8b52b16b3aaf.png)

**Comment by Riccardalina** [comment]
@christoph-menzi sali christoph, im Kommentar oben findest du das neue Icon

**Comment by christoph-menzi** [comment]
Ist angepasst. Idealerweise immer ein .svg. PNG geht in dem Fall aber auch.

**Comment by Riccardalina** [comment]
@Riccardalina: als svg senden

**Comment by Riccardalina** [comment]
@christoph-menzi : hier das svg


![heating (1)](https://user-images.githubusercontent.com/122005698/215055275-7bac3ff5-dd57-43d0-ab8c-4b65592c02ee.svg)

**Comment by christoph-menzi** [comment]
Ist ausgetauscht.

**Comment by christoph-menzi** [comment]
![image](https://user-images.githubusercontent.com/109087392/215121930-e18544fc-7bc6-4597-b2de-64297c8edf65.png)
