### ISSUE TITLE
Importfunktion: Link an Alex und Andi schicken

### ISSUE THREAD

**Issue by Abonax-SAL** [Abonax-SAL/Waermekachel-TBW#9]
Kannst Du bitte den Link für den Import an uns schicken, dass wir schon einmal neue Daten testweise importieren können und lernen, auf was zu achten ist?

**Comment by mguddelmoni** [comment]
Die Datei kann einfach über den Modx Manager hochgeladen werden. Der Dateiname muss "export.xlsx" heissen und untern im Ordner "waermedata" abgelegt werden.

Login: 
https://deineenergie-preisrechner.ch/manager/ 

Achtung! 
Das auslesen einer Excel Datei ist recht **speicherintensiv**. Also am Besten alle Formatierungen Funktionen, Filter, sVerweise entfernen um die Datei so schlank wie möglich zu halten.

Die Struktur muss beibehalten werden, dennoch schlage ich vor alle unnötigen Spalten zu entfernen. Falls Ihr dies Erwägung zieht, muss ich das Script entsprechend anpassen.
